<?php


if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_55140f49795d5',
	'title' => 'Post Type: Events',
	'fields' => array (
		array (
			'key' => 'field_5537a12c4e416',
			'label' => 'Event Start Date',
			'name' => 'event_start_date',
			'type' => 'date_picker',
			'instructions' => 'Leave this empty if the event is only one day.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'd/m/y',
			'return_format' => 'Ymd',
			'first_day' => 1,
		),
		array (
			'key' => 'field_55140f61111c1',
			'label' => 'Event End Date',
			'name' => 'event_date',
			'type' => 'date_picker',
			'instructions' => 'Choose the event end date.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'd/m/y',
			'return_format' => 'Ymd',
			'first_day' => 1,
		),
		array (
			'key' => 'field_5526c1d97ad54',
			'label' => 'Event Time',
			'name' => 'event_time',
			'type' => 'text',
			'instructions' => 'ex) 10am-11am',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_55142b0386807',
			'label' => 'Excerpt',
			'name' => 'excerpt',
			'type' => 'wysiwyg',
			'instructions' => 'This should be brief. It will show in various areas of the site.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'visual',
			'toolbar' => 'excerpt',
			'media_upload' => 0,
		),
		array (
			'key' => 'field_5526c2215da17',
			'label' => 'Address',
			'name' => 'address',
			'type' => 'textarea',
			'instructions' => 'This is just for readability. Use the google map at the bottom to locate the event on the map.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'wpautop',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_56567b889bbff',
			'label' => 'Map Zoom',
			'name' => 'map_zoom',
			'type' => 'number',
			'instructions' => 'Choose a number between 2-20. The larger the number the further zoomed in.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 7,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => 2,
			'max' => 20,
			'step' => 1,
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_5526889170962',
			'label' => 'Location',
			'name' => 'location',
			'type' => 'google_map',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'center_lat' => '',
			'center_lng' => '',
			'zoom' => '',
			'height' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'events',
			),
		),
	),
	'menu_order' => -5,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;
?>